spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        #        transaction:
        #          jta:
        #            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        #        entitymanager_factory_interface: jakarta.persistence.EntityManagerFactory
        format_sql: true        # SQL을 포맷하여 보기 좋게 출력
        use_sql_comments: true  # SQL에 주석을 추가하여, 쿼리의 의미를 더 명확히 함
        generate_statistics: true
  data:
    mongodb:
      uri: mongodb://jjh:jjh@localhost:27017/book
    redis:
      port: 6379
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/EMA
    username: joey
    password: EmaEma*#7531
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/EMA
      username: joey
      password: EmaEma*#7531
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

logging:
  level:
    org:
      hibernate: debug
      springframework:
        security: debug




