spring:
  data:
    mongodb:
      uri: mongodb://test:test@localhost:27017/test
    redis:
      port: 6379
      host: localhost

#logging:
#  config: classpath:log4j2-spring-local.yml
#  level:
#    root: info
#    feign: debug
#    com.twolinecode.com: debug


