spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
#  jmx:
#    enabled: false #Spring Boot에서 JMX를 사용하지 않는 경우

server:
  port: 8000

logging:
  level:
    #root: info # INFO 레벨 이상의 메시지만 출력하도록 설정합니다.   INFO, WARN, ERROR 레벨의 로그 메시지가 출력됩니다.  DEBUG, TRACE 레벨의 메시지는 무시됩니다.
    root: info #off error warn info debug trace